apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: customer-purchase-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: galshirizli/backend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: customer-purchase-system
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend
